//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSR.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSR.Core.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate your account.
        /// </summary>
        public static string Activare_your_account {
            get {
                return ResourceManager.GetString("Activare_your_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request.
        /// </summary>
        public static string An_error_occurred_while_processing_your_request {
            get {
                return ResourceManager.GetString("An_error_occurred_while_processing_your_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic group name for mobile already exists.
        /// </summary>
        public static string Arabic_group_name_for_mobile_already_exists {
            get {
                return ResourceManager.GetString("Arabic_group_name_for_mobile_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name Already Exists.
        /// </summary>
        public static string Arabic_name_already_exists {
            get {
                return ResourceManager.GetString("Arabic_name_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Already Exists.
        /// </summary>
        public static string Barcode_already_exists {
            get {
                return ResourceManager.GetString("Barcode_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch num already exist.
        /// </summary>
        public static string Branch_num_already_exist {
            get {
                return ResourceManager.GetString("Branch_num_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply this tax as general  tax because it linked as special tax.
        /// </summary>
        public static string Cannot_apply_this_tax_as_general_tax_because_it__linked_as_special_tax {
            get {
                return ResourceManager.GetString("Cannot_apply_this_tax_as_general_tax_because_it _linked_as_special_tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply this tax as special tax because it linked as general tax.
        /// </summary>
        public static string Cannot_apply_this_tax_as_special_tax_because_it__linked_as_general_tax {
            get {
                return ResourceManager.GetString("Cannot_apply_this_tax_as_special_tax_because_it _linked_as_general_tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t send activation email, please try registration later.
        /// </summary>
        public static string Cant_send_activation_email_please_try_registration_later {
            get {
                return ResourceManager.GetString("Cant_send_activation_email_please_try_registration_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant send forgot password email please try later.
        /// </summary>
        public static string Cant_send_forgot_password_email_please_try_later {
            get {
                return ResourceManager.GetString("Cant_send_forgot_password_email_please_try_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Already Exists.
        /// </summary>
        public static string Code_already_exists {
            get {
                return ResourceManager.GetString("Code_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Your Email.
        /// </summary>
        public static string Confirm_your_email {
            get {
                return ResourceManager.GetString("Confirm_your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Client,your workstation.
        /// </summary>
        public static string Dear_Client_your_workstation {
            get {
                return ResourceManager.GetString("Dear_Client_your_workstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Faild.
        /// </summary>
        public static string Deleted_Faild {
            get {
                return ResourceManager.GetString("Deleted_Faild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string Deleted_successfully {
            get {
                return ResourceManager.GetString("Deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string Direction_language {
            get {
                return ResourceManager.GetString("Direction_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either username and/or Email already exists.
        /// </summary>
        public static string Either_username_and_or_email_already_exists {
            get {
                return ResourceManager.GetString("Either_username_and_or_email_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English group name for mobile already exists.
        /// </summary>
        public static string English_group_name_for_mobile_already_exists {
            get {
                return ResourceManager.GetString("English_group_name_for_mobile_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name Already Exists.
        /// </summary>
        public static string English_name_already_exists {
            get {
                return ResourceManager.GetString("English_name_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password.
        /// </summary>
        public static string Forgot_your_password {
            get {
                return ResourceManager.GetString("Forgot_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free payment method already exists.
        /// </summary>
        public static string Free_payment_method_already_exists {
            get {
                return ResourceManager.GetString("Free_payment_method_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect current password.
        /// </summary>
        public static string Incorrect_current_password {
            get {
                return ResourceManager.GetString("Incorrect_current_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email doesn&apos;t exists,Please check your Email.
        /// </summary>
        public static string Invalid_email {
            get {
                return ResourceManager.GetString("Invalid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it_exceeds_the .
        /// </summary>
        public static string It_exceeds_the {
            get {
                return ResourceManager.GetString("It_exceeds_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar.
        /// </summary>
        public static string Language_abbrevation {
            get {
                return ResourceManager.GetString("Language_abbrevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي.
        /// </summary>
        public static string Language_text {
            get {
                return ResourceManager.GetString("Language_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing data.
        /// </summary>
        public static string Missing_data {
            get {
                return ResourceManager.GetString("Missing_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing new password.
        /// </summary>
        public static string Missing_new_password {
            get {
                return ResourceManager.GetString("Missing_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing old password.
        /// </summary>
        public static string Missing_old_password {
            get {
                return ResourceManager.GetString("Missing_old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing password.
        /// </summary>
        public static string Missing_password {
            get {
                return ResourceManager.GetString("Missing_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing username.
        /// </summary>
        public static string Missing_username {
            get {
                return ResourceManager.GetString("Missing_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exists.
        /// </summary>
        public static string Name_already_exists {
            get {
                return ResourceManager.GetString("Name_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password length should be 6 characters or more.
        /// </summary>
        public static string New_password_length_should_be_6_characters_or_more {
            get {
                return ResourceManager.GetString("New_password_length_should_be_6_characters_or_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string No_data_available {
            get {
                return ResourceManager.GetString("No_data_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number already exists.
        /// </summary>
        public static string Number_already_exists {
            get {
                return ResourceManager.GetString("Number_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password length should be 6 characters or more.
        /// </summary>
        public static string Old_password_length_should_be_6_characters_or_more {
            get {
                return ResourceManager.GetString("Old_password_length_should_be_6_characters_or_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length should be 6 characters or more.
        /// </summary>
        public static string Password_length_should_be_6_characters_or_more {
            get {
                return ResourceManager.GetString("Password_length_should_be_6_characters_or_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password doesn&apos;t match the password.
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method already exists.
        /// </summary>
        public static string Payment_method_already_exists {
            get {
                return ResourceManager.GetString("Payment_method_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone already used by another customer.
        /// </summary>
        public static string Phone_already_exists {
            get {
                return ResourceManager.GetString("Phone_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please activate your account by clicking.
        /// </summary>
        public static string Please_activate_your_account_by_clicking {
            get {
                return ResourceManager.GetString("Please_activate_your_account_by_clicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to activtate your account.
        /// </summary>
        public static string Please_check_your_email_to_activtate_your_email {
            get {
                return ResourceManager.GetString("Please_check_your_email_to_activtate_your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string Please_check_your_email_to_reset_your_password {
            get {
                return ResourceManager.GetString("Please_check_your_email_to_reset_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reload the page to prevent duplicate settings.
        /// </summary>
        public static string Please_reload_the_page {
            get {
                return ResourceManager.GetString("Please_reload_the_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Remove special characters.
        /// </summary>
        public static string Please_Remove_special_characters {
            get {
                return ResourceManager.GetString("Please_Remove_special_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QID already exists.
        /// </summary>
        public static string QID_already_exists {
            get {
                return ResourceManager.GetString("QID_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration is Fail.
        /// </summary>
        public static string Reigster_Model_is_null {
            get {
                return ResourceManager.GetString("Reigster_Model_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string Reset_your_password {
            get {
                return ResourceManager.GetString("Reset_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully completed.
        /// </summary>
        public static string Saved_successfully_completed {
            get {
                return ResourceManager.GetString("Saved_successfully_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image file to upload.
        /// </summary>
        public static string Select_image_file_to_upload {
            get {
                return ResourceManager.GetString("Select_image_file_to_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serila is :.
        /// </summary>
        public static string Serila_is {
            get {
                return ResourceManager.GetString("Serila_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size limit of image.
        /// </summary>
        public static string Size_limit {
            get {
                return ResourceManager.GetString("Size_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been sent to the e-mail.
        /// </summary>
        public static string The_password_has_been_sent_to_the_e_mail {
            get {
                return ResourceManager.GetString("The_password_has_been_sent_to_the_e-mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password is incorrect.
        /// </summary>
        public static string The_username_or_password_is_incorrect {
            get {
                return ResourceManager.GetString("The_username_or_password_is_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email doesnt exist.
        /// </summary>
        public static string This_Email_doesnt_exist {
            get {
                return ResourceManager.GetString("This_Email_doesnt_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This serial is related to another company, you can&apos;t use it.
        /// </summary>
        public static string This_serial_is_related_to_another_company_you_can_t_use_it {
            get {
                return ResourceManager.GetString("This_serial_is_related_to_another_company_you_can\'t_use_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This serial is used by another workstation.
        /// </summary>
        public static string This_serial_is_used_by_another_workstation {
            get {
                return ResourceManager.GetString("This_serial_is_used_by_another_workstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This serial number does not exists.
        /// </summary>
        public static string This_serial_number_does_not_exists {
            get {
                return ResourceManager.GetString("This_serial_number_does_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tax is linked with the items please disconnect the link.
        /// </summary>
        public static string This_tax_is_linked_with_items {
            get {
                return ResourceManager.GetString("This_tax_is_linked_with_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user not authorized to login.
        /// </summary>
        public static string This_user_not_authorized_to_login {
            get {
                return ResourceManager.GetString("This_user_not_authorized_to_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To reset your password click.
        /// </summary>
        public static string To_reset_your_password_click {
            get {
                return ResourceManager.GetString("To_reset_your_password_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update operation failed.
        /// </summary>
        public static string Update_operation_failed {
            get {
                return ResourceManager.GetString("Update_operation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully completed.
        /// </summary>
        public static string Updated_successfully_completed {
            get {
                return ResourceManager.GetString("Updated_successfully_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload image failed.
        /// </summary>
        public static string Upload_image_failed {
            get {
                return ResourceManager.GetString("Upload_image_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image successful.
        /// </summary>
        public static string Upload_image_successful {
            get {
                return ResourceManager.GetString("Upload_image_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have any permission for any brands.
        /// </summary>
        public static string You_dont_have_any_permission_for_any_brands {
            get {
                return ResourceManager.GetString("You_dont_have_any_permission_for_any_brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked, please try later , or you may rest your password.
        /// </summary>
        public static string Your_account_is_locked_please_try_later {
            get {
                return ResourceManager.GetString("Your_account_is_locked_please_try_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not activated, please activate it.
        /// </summary>
        public static string Your_account_is_not_activated_please_activate_it {
            get {
                return ResourceManager.GetString("Your_account_is_not_activated_please_activate_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your company account is pending,please wait until activate.
        /// </summary>
        public static string Your_company_account_is_pending {
            get {
                return ResourceManager.GetString("Your_company_account_is_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file wasn&apos;t uploaded because.
        /// </summary>
        public static string Your_file_was_not_uploaded_because {
            get {
                return ResourceManager.GetString("Your_file_was_not_uploaded_because", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed.
        /// </summary>
        public static string Your_password_has_been_changed {
            get {
                return ResourceManager.GetString("Your_password_has_been_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset..
        /// </summary>
        public static string Your_password_has_been_reset_Please {
            get {
                return ResourceManager.GetString("Your_password_has_been_reset_Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration completed successfully.
        /// </summary>
        public static string Your_registration_completed_successfully {
            get {
                return ResourceManager.GetString("Your_registration_completed_successfully", resourceCulture);
            }
        }
    }
}
